### ISSUE TITLE
Allow configuration option to skip SSL certificate verification

### ISSUE THREAD

**Issue by weissenheimer** [directus/sdk-php#40]
The Directus PHP-SDK cannot be used with self-signed SSL certificates due to an error from Guzzle:

> [Wed Nov 14 15:01:53.384591 2018] [php7:error] [pid 12] [client 172.17.0.1:35294] PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\RequestException: cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/site/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186\nStack trace:\n#0 /var/www/site/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\\Handler\\CurlFactory::createRejection(Object(GuzzleHttp\\Handler\\EasyHandle), Array)\n#1 /var/www/site/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\\Handler\\CurlFactory::finishError(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))\n#2 /var/www/site/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\\Handler\\CurlFactory::finish(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))\n#3 /var/www/site/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__in in /var/www/site/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186

However, Guzzle provides an option to disable SSL verification: 

```$client->setDefaultOption('verify', false);```

Can we have this option passed when initializing a new client instance? Something like:

```php
$client = \Directus\SDK\ClientFactory::create('user-token', [
    // Directus API Path without its version
    'base_url' => 'http://directus.local',
    'version' => '1', // Optional - default 1.1
    'verify' => false
]);
```

**Comment by WellingGuzman** [comment]
Thanks @weissenheimer, I will implement this soon. If someone else want to give this a try I can help you. here is where the Guzzle client is created: https://github.com/directus/sdk-php/blob/master/src/BaseClientRemote.php#L158
